function love.conf(t)
  t.window.title = "Side Scoller Base"  -- The window title (string)
  t.window.width = 256 * 3              -- The window width (number) 16
  t.window.height = 200 * 3             -- The window height (number) 12.5
  t.console = false                     -- Attach a console (boolean, Windows only)
  t.window.resizable = false            -- Let the window be user-resizable (boolean)
  t.window.fullscreen = false           -- Enable fullscreen (boolean)
  t.window.fullscreentype = "desktop"   -- Choose between "desktop" fullscreen or "exclusive" fullscreen mode (string)
  t.window.vsync = true                 -- Enable vertical sync (boolean)
  t.window.highdpi = false              -- Enable high-dpi mode for the window on a Retina display (boolean)
  t.modules.audio = true                -- Enable the audio module (boolean)
  t.modules.event = true                -- Enable the event module (boolean)
  t.modules.graphics = true             -- Enable the graphics module (boolean)
  t.modules.image = true                -- Enable the image module (boolean)
  t.modules.joystick = true             -- Enable the joystick module (boolean)
  t.modules.keyboard = true             -- Enable the keyboard module (boolean)
  t.modules.math = true                 -- Enable the math module (boolean)
  t.modules.mouse = true                -- Enable the mouse module (boolean)
  t.modules.physics = true              -- Enable the physics module (boolean)
  t.modules.sound = true                -- Enable the sound module (boolean)
  t.modules.system = true               -- Enable the system module (boolean)
  t.modules.timer = true                -- Enable the timer module (boolean), Disabling it will result 0 delta time in love.update
  t.modules.touch = true                -- Enable the touch module (boolean)
  t.modules.video = true                -- Enable the video module (boolean)
  t.modules.window = true               -- Enable the window module (boolean)
  t.modules.thread = true               -- Enable the thread module (boolean)
end
